# Generated by Django 5.2.16 on 2026-08-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(max_length=500)),
                ('methode', models.CharField(max_length=10)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('date_click', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de clic',
                'verbose_name_plural': 'Journal des clics',
                'ordering': ['-date_click'],
            },
        ),
    ]
