# Generated by Django 5.2.16 on 2026-08-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalClick',
        ),
    ]
